# Lab Assignment 1: Rock, Paper, Scissors

## Write and Run Your Own Code to Implement a Rock-Paper-Scissors Model

In [25]:
# Library Declarations
import numpy as np
import random

# declaring constants 
ROCK = 0
PAPER = 1
SCISSORS = 2

np.random.seed(0)
random.seed(0)

    


In [26]:
# Data extraction here: extract the data from the txt file to python input
# One suggestion is using integers 0,1,2 for rock paper scissor
# and using CPU guess, your guess and score (1 if you win; -1 if you lose; 0 for draw) as possible data
demo_data = np.loadtxt(r"./demo_data.txt", dtype=int) .reshape(-1,3)
print("The data in this file has been stored in a NumPy array of size {}.".format(demo_data.shape))
print(demo_data)

The data in this file has been stored in a NumPy array of size (5, 3).
[[ 0  1  1]
 [ 0  2 -1]
 [ 1  0 -1]
 [ 2  0  1]
 [ 0  0  0]]


### Training Data Generation 

For this assignment, I generated the training data by personally playing rock–paper–scissors against the computer for 100 rounds and manually recording the outcomes. This approach ensured that the data reflected a consistent decision-making style and a single set of behavioral patterns.

If multiple people each generated a small amount of training data, the resulting dataset would likely contain a mixture of different strategies, habits, and biases. While this could increase diversity in the data, it may also make it harder for a simple model to learn clear patterns, especially with a limited number of total rounds. Conflicting tendencies across players could introduce noise and reduce the effectiveness of pattern exploitation.


In [27]:
from collections import Counter

np.random.seed(0)
random.seed(0)

history = np.loadtxt(r"./training.txt", dtype=int).reshape(-1,3)

print(history)
#Define your algorithm here or define your own functions and procedure

# create a data structure to store the best play to beat a tool
# 0 - rock, 1-paper, 2 - scissors
best_play = {0:1, 1:2, 2:0}
prob_given = {0:{0:0,1:0,2:0},1:{0:0,1:0,2:0},2:{0:0,1:0,2:0}}
def rock_paper_scissor(history=None, last_choice=None):
    # define your function here
    
    # if there is no history or only two plays stored, randomly choose a tool 
    if history is None or len(history) < 2:
        return random.randint(0,2)
    
    # training based on history
    
    # extract the CPU's choices [cpu, your move, score]
    cpu = []
    for i in range(len(history) - 1):
        current_tool = history[i][0]
        next_tool = history[i + 1][0]

        prob_given[current_tool][next_tool] += 1

    
    # Look at the opponent's most recent move
    if last_choice is None:
        last_tool = history[-1][0]
    else:
        last_tool = last_choice

    # Predict the opponent's next move (most frequent transition)
    predicted_next = max(
        prob_given[last_tool],
        key=prob_given[last_tool].get
    )
    print(prob_given)
    return best_play[predicted_next]


[[ 0  0  0]
 [ 2  1 -1]
 [ 0  0  0]
 [ 0  2 -1]
 [ 2  1 -1]
 [ 1  2  1]
 [ 1  1  0]
 [ 1  1  0]
 [ 2  1 -1]
 [ 0  0  0]
 [ 1  1  0]
 [ 0  2 -1]
 [ 2  1 -1]
 [ 0  1  1]
 [ 0  0  0]
 [ 1  2  1]
 [ 2  0  1]
 [ 2  1 -1]
 [ 1  1  0]
 [ 2  0  1]
 [ 1  0 -1]
 [ 1  2  1]
 [ 0  1  1]
 [ 1  2  1]
 [ 1  1  0]
 [ 1  0 -1]
 [ 2  2  0]
 [ 2  0  1]
 [ 2  2  0]
 [ 1  1  0]
 [ 2  0  1]
 [ 0  0  0]
 [ 1  0 -1]
 [ 0  2 -1]
 [ 2  1 -1]
 [ 1  2  1]
 [ 1  0 -1]
 [ 2  2  0]
 [ 2  1 -1]
 [ 0  0  0]
 [ 0  2 -1]
 [ 2  1 -1]
 [ 1  0 -1]
 [ 2  2  0]
 [ 0  2 -1]
 [ 2  1 -1]
 [ 0  0  0]
 [ 1  0 -1]
 [ 1  2  1]
 [ 0  1  1]
 [ 1  0 -1]
 [ 0  1  1]
 [ 0  2 -1]
 [ 2  0  1]
 [ 2  1 -1]
 [ 0  0  0]
 [ 1  1  0]
 [ 0  0  0]
 [ 0  2 -1]
 [ 2  0  1]
 [ 1  1  0]
 [ 2  1 -1]
 [ 0  0  0]
 [ 1  1  0]
 [ 0  0  0]
 [ 0  1  1]
 [ 0  2 -1]
 [ 2  1 -1]
 [ 1  2  1]
 [ 1  0 -1]
 [ 2  1 -1]
 [ 0  0  0]
 [ 0  1  1]
 [ 0  0  0]
 [ 2  2  0]
 [ 2  0  1]
 [ 2  2  0]
 [ 1  1  0]
 [ 0  0  0]
 [ 0  1  1]
 [ 0  0  0]
 [ 2  2  0]
 [ 0  2 -1]
 [ 0

In [28]:
print(f'Algorithm says you should choose: {rock_paper_scissor(history)}')

{0: {0: 16, 1: 9, 2: 12}, 1: {0: 9, 1: 8, 2: 11}, 2: {0: 11, 1: 11, 2: 12}}
Algorithm says you should choose: 0


# Testing the model

In [29]:
move_names = {0: "rock", 1: "paper", 2: "scissors"}

evaluation_data = []
wins = losses = ties = 0

last_cpu_move = None  # track opponent's most recent move

for i in range(100):
    print(f"\nRound {i+1}")

    model_move = rock_paper_scissor(history, last_choice=last_cpu_move)
    print("Model recommends:", move_names[model_move])

    cpu_input = input("Enter computer move (rock/paper/scissors): ").strip().lower()
    cpu_move = {"rock": 0, "paper": 1, "scissors": 2}[cpu_input]
    
    # determining the outcome of the round
    if model_move == cpu_move:
        score = 0
        ties += 1
    elif (model_move - cpu_move) % 3 == 1:
        score = 1
        wins += 1
    else:
        score = -1
        losses += 1

    evaluation_data.append([cpu_move, model_move, score])

    # update history and last move
    history = np.vstack([history, [cpu_move, model_move, score]])
    last_cpu_move = cpu_move



Round 1
{0: {0: 32, 1: 18, 2: 24}, 1: {0: 18, 1: 16, 2: 22}, 2: {0: 22, 1: 22, 2: 24}}
Model recommends: rock


KeyboardInterrupt: Interrupted by user

In [ ]:


np.savetxt("evaluation.txt", evaluation_data, fmt="%d")
print(f"Wins: {wins}, Losses: {losses}, Ties: {ties}")


Wins: 23, Losses: 56, Ties: 21


# Model Evaluation

The model was evaluated over 100 additional rounds of play against the computer, using the trained transition-based strategy to recommend moves. While the model did not consistently outperform the computer, it demonstrated the ability to adapt its predictions based on observed opponent behavior. These results highlight both the potential and limitations of a simple first-order prediction model in a non-stationary environment.

# Reflection 

This lab helped me understand how simple algorithms can learn from data by adapting to patterns in past behavior. I also learned the importance of testing a model and thinking about why it works or fails, rather than focusing only on performance.

## What to Submit?

**Note: This is the first assignment, designed to help you get familiar with the GitHub workflow.**

**For this assignment only**, please submit a `.zip` file containing:
1. Your training data in `training.txt`.
2. Your model evaluation data.
3. A brief write-up describing your algorithm in a couple of sentences, including figures if necessary (your design on paper).
4. Finally, please individually briefly reflect on your experience in a couple of sentences. What are you taking away from this lab?

**Starting from Assignment 2**: Next week, we will release a Google Sheet assigning each student a Lab TA. From Assignment 2 onwards, you will need to:
- Submit a link to your GitHub repository (instead of a .zip file)
- Add your assigned Lab TA as a collaborator to your repository, or they won't be able to grade your work! 